/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.banditoz.gmecord;

import javax.security.auth.login.LoginException;

public class Main {
    public static void main(String[] args) throws LoginException, InterruptedException {
        new Bot();
    }
}
